name: Enforce Canonical Links

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make scripts executable
        run: |
          chmod +x scripts/check-links.sh || true

      - name: Verify canonical links and defaults
        run: |
          bash scripts/check-links.sh
